language: python
sudo: enabled
cache: pip
python:
    - '3.5'

services:
    - mysql:5.7

env:
    - FLASK_ENV=testing

install:
    - pip install -r test_requirements.txt -U

before_script:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root_quatrains') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - mysql -e 'create database quatrains character set utf8mb4 collate utf8mb4_unicode_ci'

script:
    - pytest tests
